### ISSUE TITLE
Cannot pip install on Windows for Python 3.8

### ISSUE THREAD

**Issue by Knightowl3128** [frescobaldi/python-poppler-qt5#46]
This is the error I got.
```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nr\appdata\local\programs\python\python38\python.exe' 'c:\users\nr\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\NAVANE~1\AppData\Local\Temp\tmpl2ofr68s'
         cwd: C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_14fb155b4f024ed2aaa88cf0408bde0b
    Complete output (29 lines):
    Traceback (most recent call last):
      File "c:\users\nr\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\nr\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
        main()
      File "c:\users\nr\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\users\nr\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "c:\users\nr\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "C:\Users\nr\AppData\Local\Temp\pip-build-env-1h9o6_ak\overlay\Lib\site-packages\sipbuild\api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "C:\Users\nr\AppData\Local\Temp\pip-build-env-1h9o6_ak\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "C:\Users\nr\AppData\Local\Temp\pip-build-env-1h9o6_ak\overlay\Lib\site-packages\sipbuild\project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "C:\Users\nr\AppData\Local\Temp\pip-build-env-1h9o6_ak\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "C:\Users\nr\AppData\Local\Temp\pip-build-env-1h9o6_ak\overlay\Lib\site-packages\sipbuild\project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "C:\Users\nr\AppData\Local\Temp\pip-build-env-1h9o6_ak\overlay\Lib\site-packages\pyqtbuild\builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/70/13/264e20336f7951044a8dd49cb1460bd318e2ebacff1753f908e6544ec933/python-poppler-qt5-21.1.0.tar.gz#sha256=add766db2c04026a6087f38f2044e66c8b053c81002f3753d8059713497d022d (from https://pypi.org/simple/python-poppler-qt5/). Command errored out with exit status 1: 'c:\users\nr\appdata\local\programs\python\python38\python.exe' 'c:\users\nr\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\NAVANE~1\AppData\Local\Temp\tmpl2ofr68s' Check the logs for full command output.
  Using cached python-poppler-qt5-0.75.0.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nr\appdata\local\programs\python\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_e21bf3fa589b46e88d7613f40c6fc03a\\setup.py'"'"'; __file__='"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_e21bf3fa589b46e88d7613f40c6fc03a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\nr\AppData\Local\Temp\pip-pip-egg-info-u4ilz46w'
         cwd: C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_e21bf3fa589b46e88d7613f40c6fc03a\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_e21bf3fa589b46e88d7613f40c6fc03a\setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/7d/65a14ece5dd6a1564b576c1ca30b0f5639be64cc55b62b4d2b497159ed43/python-poppler-qt5-0.75.0.tar.gz#sha256=ea0ec9ebe995705ab19a301290365652e62bab5c9b05db5697c7bf2173335107 (from https://pypi.org/simple/python-poppler-qt5/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached python-poppler-qt5-0.74.0.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nr\appdata\local\programs\python\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_8c1afe86bb7b489b953def00accd0a5d\\setup.py'"'"'; __file__='"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_8c1afe86bb7b489b953def00accd0a5d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\nr\AppData\Local\Temp\pip-pip-egg-info-snj3p98s'
         cwd: C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_8c1afe86bb7b489b953def00accd0a5d\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_8c1afe86bb7b489b953def00accd0a5d\setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c0/74/1479a3435ce3a68cb6f1de7cd60398c480893bcb5f6d7be2b7fa4c58f7a6/python-poppler-qt5-0.74.0.tar.gz#sha256=a21ad645d32c7544782587a01530378ff2718ad007a4ad5279a9783935a6086c (from https://pypi.org/simple/python-poppler-qt5/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached python-poppler-qt5-0.24.2.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nr\appdata\local\programs\python\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_ee34ab8ec3d24b768040d065f2cef45d\\setup.py'"'"'; __file__='"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_ee34ab8ec3d24b768040d065f2cef45d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\nr\AppData\Local\Temp\pip-pip-egg-info-ip21iy8j'
         cwd: C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_ee34ab8ec3d24b768040d065f2cef45d\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_ee34ab8ec3d24b768040d065f2cef45d\setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/af/e7/aa451d4ca0910472c4442d8aa6ef44300852926d85ad033b029a22157027/python-poppler-qt5-0.24.2.tar.gz#sha256=3970c35ce1f0f1464a6c2746bea4c479b9780b4e17030c92479f7f1738a5c950 (from https://pypi.org/simple/python-poppler-qt5/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached python-poppler-qt5-0.24.1.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nr\appdata\local\programs\python\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_b21e9e1843204891be5bb719bada01d4\\setup.py'"'"'; __file__='"'"'C:\\Users\\nr\\AppData\\Local\\Temp\\pip-install-3q_63930\\python-poppler-qt5_b21e9e1843204891be5bb719bada01d4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\nr\AppData\Local\Temp\pip-pip-egg-info-gjg4owbd'
         cwd: C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_b21e9e1843204891be5bb719bada01d4\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nr\AppData\Local\Temp\pip-install-3q_63930\python-poppler-qt5_b21e9e1843204891be5bb719bada01d4\setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/26/41/81e7ee90baeeee2a5179af742edbac621ebf58d66b980f55547ef21e58f8/python-poppler-qt5-0.24.1.tar.gz#sha256=4254c4d5a1a76b13f8350815c90693bccee4705f4a1c8ad1021dd79f6b008c84 (from https://pypi.org/simple/python-poppler-qt5/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement python-poppler-qt5 (from versions: 0.24.1, 0.24.2, 0.74.0, 0.75.0, 21.1.0)
ERROR: No matching distribution found for python-poppler-qt5
```

**Comment by jeanas** [comment]
python-poppler-qt5 does not currently have prebuilt versions on PyPI, so pip tries to install it from source, which fails in your case because you're missing the `qmake` build tool (and perhaps other dependencies like Poppler itself). These can be installed on Anaconda or Miniconda using Conda.

I will close this issue; see #42 to track the progress of making prebuilt versions.
