### ISSUE TITLE
ModuleNotFoundError: No module named 'sipdistutils'

### ISSUE THREAD

**Issue by RillonDodgers** [frescobaldi/python-poppler-qt5#48]
### Description 
When installing `python-poppler-qt5` using `pip3 install python-poppler-qt5` I get this error stated in the title of this issue. However, when installing the module by using `pip3 install git+https://github.com/frescobaldi/python-poppler-qt5.git`, it installs perfectly fine. pypi and the one installed using the git method both show a version of `21.1.0`

### Errored Install:
```
Collecting python-poppler-qt5
  Downloading python-poppler-qt5-21.1.0.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python /home/vagrant/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpunwefy62
         cwd: /tmp/pip-install-7yk12_tt/python-poppler-qt5_14f13cf3ca1d41d1b369c66a4e4f7f14
    Complete output (6 lines):
    Querying qmake about your Qt installation...
    /usr/bin/qmake -query
    These bindings will be built: Poppler-Qt5.
    Generating the Poppler-Qt5 bindings...
    _in_process.py: poppler-form.sip:152: ::Poppler::FormFieldChoice::choicesWithExportValues() unsupported function return type - provide %MethodCode and a C++ signature
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/70/13/264e20336f7951044a8dd49cb1460bd318e2ebacff1753f908e6544ec933/python-poppler-qt5-21.1.0.tar.gz#sha256=add766db2c04026a6087f38f2044e66c8b053c81002f3753d8059713497d022d (from https://pypi.org/simple/python-poppler-qt5/). Command errored out with exit status 1: /usr/bin/python /home/vagrant/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpunwefy62 Check the logs for full command output.
  Downloading python-poppler-qt5-0.75.0.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7yk12_tt/python-poppler-qt5_bac1ce8621904755b3abc8b90dacc52c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7yk12_tt/python-poppler-qt5_bac1ce8621904755b3abc8b90dacc52c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6f_18u1d
         cwd: /tmp/pip-install-7yk12_tt/python-poppler-qt5_bac1ce8621904755b3abc8b90dacc52c/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7yk12_tt/python-poppler-qt5_bac1ce8621904755b3abc8b90dacc52c/setup.py", line 42, in <module>
        import sipdistutils
    ModuleNotFoundError: No module named 'sipdistutils'
```

### Successful install:
```
[vagrant@pyqt src]$ pip3 install git+https://github.com/frescobaldi/python-poppler-qt5.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/frescobaldi/python-poppler-qt5.git
  Cloning https://github.com/frescobaldi/python-poppler-qt5.git to /tmp/pip-req-build-py53ysr3
  Running command git clone -q https://github.com/frescobaldi/python-poppler-qt5.git /tmp/pip-req-build-py53ysr3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: PyQt5 in /home/vagrant/.local/lib/python3.9/site-packages (from python-poppler-qt5==21.1.0) (5.15.4)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /home/vagrant/.local/lib/python3.9/site-packages (from python-poppler-qt5==21.1.0) (12.9.0)
Requirement already satisfied: PyQt5-Qt5>=5.15 in /home/vagrant/.local/lib/python3.9/site-packages (from PyQt5->python-poppler-qt5==21.1.0) (5.15.2)
Building wheels for collected packages: python-poppler-qt5
  Building wheel for python-poppler-qt5 (PEP 517) ... done
  Created wheel for python-poppler-qt5: filename=python_poppler_qt5-21.1.0-cp39-cp39-manylinux2014_x86_64.whl size=182653 sha256=91304c5dfc47d52a32a6c884af2198a8b51ca553eece088ae81e85aa36cf70d0
  Stored in directory: /tmp/pip-ephem-wheel-cache-lfq8oqqq/wheels/6d/e8/ce/92e5b898251529122baa575b2bd6be160a05f66fd8d4e3f81a
Successfully built python-poppler-qt5
Installing collected packages: python-poppler-qt5
Successfully installed python-poppler-qt5-21.1.0
```

**Comment by RillonDodgers** [comment]
Hopefully some more helpful information:
the issue and workaround are both reproducible on Ubuntu 20.04 and Manjaro

**Comment by rxchen** [comment]
I have the same problem,
OS: windows 10
Python: 3.9

**Comment by vitlav** [comment]
sipdistutils is obsoleted and is no more distributed in SIP5, see
https://github.com/frescobaldi/python-poppler-qt5/pull/41

**Comment by jeanas** [comment]
The fix has been released, closing.
